# LAB4 Submission
**Name:** Rediet Girmay  
**ID:** GSE/0945-17  
**Date:** 25 Sep 2025  

#**Learning in Graphical Models**

##**1. Parameter learning in Bayesian networks**

In [1]:
!pip install pgmpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 13.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 756.0/756.0 kB 26.3 MB/s eta 0:00:00


###**1.1. The maximum likelihood estimation**

In [2]:
import numpy as np
import pandas as pd
from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.estimators import MaximumLikelihoodEstimator

In [3]:
# Generating some random data
raw_data = np.random.randint(low=0, high=2, size=(100, 2))
print(raw_data)

[[1 1]
 [0 0]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 1]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [0 1]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [0 0]]


In [4]:
data = pd.DataFrame(raw_data, columns=['X', 'Y'])
print(data)

    X  Y
0   1  1
1   0  0
2   1  0
3   0  1
4   1  0
.. .. ..
95  1  0
96  1  0
97  1  0
98  1  1
99  0  0

[100 rows x 2 columns]


In [5]:
# Two coin tossing model assuming that they are dependent.
coin_model = DiscreteBayesianNetwork([('X', 'Y')])
coin_model.fit(data, estimator=MaximumLikelihoodEstimator)
cpd_x = coin_model.get_cpds('X')
print(cpd_x)

+------+------+
| X(0) | 0.55 |
+------+------+
| X(1) | 0.45 |
+------+------+


In [6]:
cpd_y = coin_model.get_cpds('Y')
print(cpd_y)

+------+---------------------+--------------------+
| X    | X(0)                | X(1)               |
+------+---------------------+--------------------+
| Y(0) | 0.5818181818181818  | 0.5777777777777777 |
+------+---------------------+--------------------+
| Y(1) | 0.41818181818181815 | 0.4222222222222222 |
+------+---------------------+--------------------+


In [7]:
raw_data = np.random.randint(low=0, high=2, size=(1000, 6))
data = pd.DataFrame(raw_data, columns=['A', 'R', 'J', 'G', 'L', 'Q'])
student_model = DiscreteBayesianNetwork([('A', 'J'), ('R', 'J'),
                                           ('J', 'Q'), ('J', 'L'),
                                             ('G', 'L')])
student_model.fit(data, estimator=MaximumLikelihoodEstimator)
student_model.get_cpds()

[<TabularCPD representing P(A:2) at 0x7fa1d37fe780>,
 <TabularCPD representing P(J:2 | A:2, R:2) at 0x7fa1d37fe6f0>,
 <TabularCPD representing P(R:2) at 0x7fa1d37ff2c0>,
 <TabularCPD representing P(Q:2 | J:2) at 0x7fa1d37ff080>,
 <TabularCPD representing P(L:2 | G:2, J:2) at 0x7fa1d37ff0b0>,
 <TabularCPD representing P(G:2) at 0x7fa1d37fecf0>]

In [8]:
for cpd in student_model.get_cpds():
    print(cpd)

+------+-------+
| A(0) | 0.488 |
+------+-------+
| A(1) | 0.512 |
+------+-------+
+------+---------------------+-----+---------------------+
| A    | A(0)                | ... | A(1)                |
+------+---------------------+-----+---------------------+
| R    | R(0)                | ... | R(1)                |
+------+---------------------+-----+---------------------+
| J(0) | 0.5080645161290323  | ... | 0.45864661654135336 |
+------+---------------------+-----+---------------------+
| J(1) | 0.49193548387096775 | ... | 0.5413533834586466  |
+------+---------------------+-----+---------------------+
+------+-------+
| R(0) | 0.494 |
+------+-------+
| R(1) | 0.506 |
+------+-------+
+------+--------------------+---------------------+
| J    | J(0)               | J(1)                |
+------+--------------------+---------------------+
| Q(0) | 0.5364891518737672 | 0.48884381338742394 |
+------+--------------------+---------------------+
| Q(1) | 0.4635108481262327 | 0.5111561

###**1.2. Bayesian parameter estimation**

In [9]:
import numpy as np
import pandas as pd
from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.estimators import BayesianEstimator

In [10]:
# Generating some random data
raw_data = np.random.randint(low=0, high=2, size=(1000, 6))
print(raw_data)

[[1 1 1 0 0 0]
 [0 1 1 0 1 0]
 [0 1 0 0 1 0]
 ...
 [0 0 0 0 1 0]
 [1 0 1 0 0 0]
 [1 0 1 1 1 0]]


In [11]:
data = pd.DataFrame(raw_data, columns=['A', 'R', 'J', 'G', 'L', 'Q'])

In [12]:
# Creating the network structures
student_model = DiscreteBayesianNetwork([('A', 'J'), ('R', 'J'),
                               ('J', 'Q'), ('J', 'L'),
                               ('G', 'L')])
student_model.fit(data, estimator=BayesianEstimator)
student_model.get_cpds()

[<TabularCPD representing P(A:2) at 0x7fa1d7508d10>,
 <TabularCPD representing P(J:2 | A:2, R:2) at 0x7fa1d3962870>,
 <TabularCPD representing P(Q:2 | J:2) at 0x7fa1d3961bb0>,
 <TabularCPD representing P(L:2 | G:2, J:2) at 0x7fa1d37fe750>,
 <TabularCPD representing P(R:2) at 0x7fa1d37fe870>,
 <TabularCPD representing P(G:2) at 0x7fa1d37ff110>]

In [13]:
print(student_model.get_cpds('G'))

+------+---------+
| G(0) | 0.50199 |
+------+---------+
| G(1) | 0.49801 |
+------+---------+


##**2. Structure learning in Bayesian networks**

###**2.1. Score-based Structure Learning**

**Scoring functions**

In [14]:
import pandas as pd
import numpy as np
from pgmpy.estimators import BDeu, K2, BIC
from pgmpy.models import DiscreteBayesianNetwork

# create random data sample with 3 variables, where Z is dependent on X, Y:
data = pd.DataFrame(np.random.randint(0, 4, size=(5000, 2)), columns=list('XY'))
data['Z'] = data['X'] + data['Y']

bdeu = BDeu(data, equivalent_sample_size=5)
k2 = K2(data)
bic = BIC(data)

model1 = DiscreteBayesianNetwork([('X', 'Z'), ('Y', 'Z')])  # X -> Z <- Y
model2 = DiscreteBayesianNetwork([('X', 'Z'), ('X', 'Y')])  # Y <- X -> Z


print(bdeu.score(model1))
print(k2.score(model1))
print(bic.score(model1))

print(bdeu.score(model2))
print(k2.score(model2))
print(bic.score(model2))


-13939.07994147509
-14329.883246877449
-14295.119637506323
-20903.203947624494
-20930.03604552637
-20947.248825423798


In [15]:
print(bdeu.local_score('Z', parents=[]))
print(bdeu.local_score('Z', parents=['X']))
print(bdeu.local_score('Z', parents=['X', 'Y']))

-9199.449565526675
-6992.417676649053
-57.1199102237253


**Search strategies**

In [16]:
from pgmpy.estimators import ExhaustiveSearch

es = ExhaustiveSearch(data, scoring_method=bic)
best_model = es.estimate()
print(best_model.edges())

print("\nAll DAGs by score:")
for score, dag in reversed(es.all_scores()):
    print(score, dag.edges())

[('X', 'Z'), ('Y', 'Z')]

All DAGs by score:
-14295.119637506323 [('X', 'Z'), ('Y', 'Z')]
-14328.045592300805 [('Y', 'X'), ('Z', 'X'), ('Z', 'Y')]
-14328.045592300805 [('X', 'Z'), ('Y', 'Z'), ('Y', 'X')]
-14328.045592300805 [('X', 'Y'), ('Z', 'X'), ('Z', 'Y')]
-14328.045592300805 [('X', 'Y'), ('X', 'Z'), ('Z', 'Y')]
-14328.045592300807 [('Y', 'Z'), ('Y', 'X'), ('Z', 'X')]
-14328.045592300807 [('X', 'Y'), ('X', 'Z'), ('Y', 'Z')]
-16503.348562795192 [('X', 'Y'), ('Z', 'Y')]
-16505.05298321283 [('Y', 'X'), ('Z', 'X')]
-18737.315479717287 [('Z', 'X'), ('Z', 'Y')]
-18737.31547971729 [('Y', 'Z'), ('Z', 'X')]
-18737.31547971729 [('X', 'Z'), ('Z', 'Y')]
-20912.618450211674 [('Z', 'Y')]
-20912.61845021168 [('Y', 'Z')]
-20914.322870629312 [('Z', 'X')]
-20914.322870629312 [('X', 'Z')]
-20945.544405006156 [('Y', 'X'), ('Z', 'Y')]
-20945.544405006163 [('Y', 'Z'), ('Y', 'X')]
-20945.544405006163 [('X', 'Y'), ('Y', 'Z')]
-20947.248825423794 [('X', 'Z'), ('Y', 'X')]
-20947.248825423794 [('X', 'Y'), ('

In [17]:
from pgmpy.estimators import HillClimbSearch

# create some data with dependencies
data = pd.DataFrame(np.random.randint(0, 3, size=(2500, 8)), columns=list('ABCDEFGH'))
data['A'] += data['B'] + data['C']
data['H'] = data['G'] - data['A']

hc = HillClimbSearch(data)
best_model = hc.estimate(scoring_method=BIC(data))
print(best_model.edges())

  0%|          | 0/1000000 [00:00<?, ?it/s]

[('A', 'H'), ('A', 'C'), ('A', 'B'), ('C', 'B'), ('G', 'H')]


###**2.2. Constraint-based Structure Learning**

In [18]:
from pgmpy.estimators import PC
from pgmpy.estimators.CITests import chi_square

data = pd.DataFrame(np.random.randint(0, 3, size=(2500, 8)), columns=list('ABCDEFGH'))
data['A'] += data['B'] + data['C']
data['H'] = data['G'] - data['A']
data['E'] *= data['F']

print(chi_square(X='B', Y='H', Z=[], data=data, significance_level=0.05))          # dependent
print(chi_square(X='B', Y='E', Z=[], data=data, significance_level=0.05))          # independent
print(chi_square(X='B', Y='H', Z=['A'], data=data, significance_level=0.05))       # independent
print(chi_square(X='A', Y='G', Z=[], data=data, significance_level=0.05))          # independent
print(chi_square(X='A', Y='G', Z=['H'], data=data, significance_level=0.05))       # dependent

False
True
True
True
False


In [19]:
est  = PC(data)
pdag = est.estimate(significance_level=0.01)
print("PDAG edges:", pdag.edges())

dag  = pdag.to_dag()
print("DAG edges :", dag.edges())

  0%|          | 0/5 [00:00<?, ?it/s]

PDAG edges: [('G', 'H'), ('C', 'A'), ('A', 'H'), ('B', 'A'), ('F', 'E'), ('E', 'F')]
DAG edges : [('G', 'H'), ('C', 'A'), ('A', 'H'), ('B', 'A'), ('E', 'F')]


##**2.3. Hybrid Structure Learning**

In [20]:
from pgmpy.estimators import MmhcEstimator
from pgmpy.estimators import BDeu

data = pd.DataFrame(np.random.randint(0, 3, size=(2500, 8)), columns=list('ABCDEFGH'))
data['A'] += data['B'] + data['C']
data['H'] = data['G'] - data['A']
data['E'] *= data['F']

mmhc  = MmhcEstimator(data)

model = mmhc.estimate(
    scoring_method=BDeu(data, equivalent_sample_size=10),  # score-based phase
    significance_level=0.01,   # CI-test α for MMPC (skeleton)
    tabu_length=10,            # hill-climb meta-heuristic
)

print("MMHC DAG edges:", model.edges())

  0%|          | 0/1000000 [00:00<?, ?it/s]

MMHC DAG edges: [('A', 'C'), ('A', 'B'), ('C', 'B'), ('E', 'F'), ('G', 'A'), ('G', 'H'), ('H', 'A')]


# **Exercise Solution: Structure Learning on Tips Dataset**

In [25]:
import seaborn as sns
import matplotlib.pyplot as plt

## **2. Loading and Preprocessing the Dataset**

In [33]:
# Load and preprocess the tips dataset
tips_data = sns.load_dataset('tips')

# Discretize continuous variables
tips_data['total_bill_cat'] = pd.cut(tips_data['total_bill'], bins=3, labels=[0, 1, 2])
tips_data['tip_cat'] = pd.cut(tips_data['tip'], bins=3, labels=[0, 1, 2])
tips_data['size_cat'] = tips_data['size'].astype('category')

# Select and encode discrete variables
discrete_columns = ['sex', 'smoker', 'day', 'time', 'total_bill_cat', 'tip_cat', 'size_cat']
encoded_data = tips_data[discrete_columns].apply(lambda x: x.cat.codes)

print("Preprocessed data shape:", encoded_data.shape)

Preprocessed data shape: (244, 7)


## **3. Learn structure using HillClimSearch with BIC and PC algorithm**

### Structure Learning with HillClimbSearch adn BIC

In [34]:
# Learn structure using HillClimbSearch with BIC
hc_estimator = HillClimbSearch(encoded_data)
hc_model = hc_estimator.estimate(scoring_method=BIC(encoded_data))
print("HillClimbSearch + BIC edges:", hc_model.edges())

  0%|          | 0/1000000 [00:00<?, ?it/s]

HillClimbSearch + BIC edges: [('day', 'time'), ('day', 'smoker'), ('time', 'sex'), ('total_bill_cat', 'tip_cat'), ('size_cat', 'total_bill_cat')]


### Structure Learning with PC Algorithm

In [35]:
# Learn structure using PC algorithm
pc_estimator = PC(encoded_data)
pc_model = pc_estimator.estimate(significance_level=0.05).to_dag()
print("PC Algorithm edges:", pc_model.edges())

  0%|          | 0/5 [00:00<?, ?it/s]

PC Algorithm edges: [('smoker', 'day'), ('time', 'day'), ('total_bill_cat', 'tip_cat'), ('size_cat', 'total_bill_cat')]


## **4. Comparison of Both Learned Structures**

In [36]:
# Compare the learned structures
hc_edges = set(hc_model.edges())
pc_edges = set(pc_model.edges())

common_edges = hc_edges.intersection(pc_edges)
hc_only = hc_edges - pc_edges
pc_only = pc_edges - hc_edges

print("\n=== COMPARISON RESULTS ===")
print(f"Common edges ({len(common_edges)}): {common_edges}")
print(f"Only in HillClimbSearch ({len(hc_only)}): {hc_only}")
print(f"Only in PC Algorithm ({len(pc_only)}): {pc_only}")
print(f"Jaccard Similarity: {len(common_edges)/len(hc_edges.union(pc_edges)):.3f}")


=== COMPARISON RESULTS ===
Common edges (2): {('total_bill_cat', 'tip_cat'), ('size_cat', 'total_bill_cat')}
Only in HillClimbSearch (3): {('day', 'smoker'), ('time', 'sex'), ('day', 'time')}
Only in PC Algorithm (2): {('smoker', 'day'), ('time', 'day')}
Jaccard Similarity: 0.286


## **Conclusion**

In our analysis of the tips dataset, we found that both learning methods discovered meaningful patterns, but in different ways. HillClimbSearch with BIC built a more detailed network, finding multiple connections between variables as it searched for the best-scoring structure. The PC algorithm took a more cautious approach, only keeping relationships that passed strict statistical tests.

This shows us an important lesson: HillClimbSearch gives us a comprehensive picture but might include some weaker connections, while PC algorithm gives us a simpler, more reliable network. The choice depends on whether you want to explore all possible relationships or focus only on the strongest ones. Both methods agreed on the core patterns, confirming that things like bill amount really do influence tipping behavior.